---
version: "2.1"
services:
  mycroft:
    image: dony71/mycroft:latest
    container_name: mycroft
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/snd:/dev/snd
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
      - /dev/i2c-1:/dev/i2c-1
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
    #user: "${UID}:${GID}"
    #group_add:
    #  - gpio
    #  - i2c
    #  - spi
    environment:
      #- PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PULSE_SERVER=unix:/run/user/1001/pulse/native
    volumes:
      - /home/pi/docker/mycroft:/root/.mycroft
      #- ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - /run/user/1001/pulse/native:/run/user/1001/pulse/native
      - /home/pi/.config/pulse/cookie:/root/.config/pulse/cookie
      #- /etc/udev/rules.d/99-com.rules:/etc/udev/rules.d/99-com.rules
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices/platform/soc/fe200000.gpio:/sys/devices/platform/soc/fe200000.gpio
    ports:
      - 1883:8181
